name: Run Perl Script

on:
  workflow_dispatch:

jobs:
  run-perl-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.32'

    - name: Install dependencies
      run: |
        cpanm --installdeps .
        cpanm Algorithm::MarkovChain
        cpanm Path::Class

    - name: Run Perl script
      run: |
        perl markov.pl
